### ISSUE TITLE
Use meaningful example in choropleth tutorial

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/gisfirstaid#11]
This currently uses and toy example: 
http://gisfirstaid.netlify.com/2017/08/31/choropleths/

It's a bit fun, but doesn't look very serious, and it is using Sierra Leone again. It would be great to showcase something more meaningful, on a different place, or just remove this part?

**Comment by dirkschumacher** [comment]
See 5b2acee1238e497c0c67656ff391877c7ec6ab63

**Comment by thibautjombart** [comment]
Tried fixing via 9daa45cdd475b49ea76248e133dbb37b5e76088d
